# Generated by Django 3.2 on 2023-02-20 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='category',
            new_name='categorie',
        ),
    ]
