# Generated by Django 3.2 on 2023-02-20 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_rename_category_title_categorie'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='genretitle',
            name='unique_genre',
        ),
    ]
